### ISSUE TITLE
Support webpack 2

### ISSUE THREAD

**Issue by satazor** [Karify/external-svg-sprite-loader#10]
It passed some time since 2.2 final release was published. Currently, this plugin does not work on 2.2:

```js
Error: Cannot find module 'webpack/lib/OriginalSource'
```

**Comment by bensampaio** [comment]
I will look into this on the coming days. Thank you!

**Comment by satazor** [comment]
@bensampaio thanks for looking into this. Here's why I prefer this loader over others: https://github.com/moxystudio/react-with-moxy/issues/4

**Comment by bensampaio** [comment]
Version 2 was just released. It should be compatible with webpack 2. There are no configuration changes but since there was a breaking change that would not work for webpack 1 I decided for a major release.

Let me know if there are any problems with it! Thank you ;)

**Comment by satazor** [comment]
It's working! Ty
